//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activitylog
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Module { get; set; }
        public string View { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string Exception { get; set; }
        public System.DateTime LogTime { get; set; }
    
        public virtual user user { get; set; }
        public virtual client client { get; set; }
    }
}
