//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advertisementcas
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<System.DateTime> AdStartDate { get; set; }
        public Nullable<System.DateTime> AdEndDate { get; set; }
        public string AdType { get; set; }
        public Nullable<int> PlacedBy { get; set; }
        public string PublicationName { get; set; }
        public Nullable<int> PublicationCirculation { get; set; }
        public string ProgramName { get; set; }
        public Nullable<float> CostIndiviualRate { get; set; }
        public Nullable<float> CostGroupRate { get; set; }
        public string TopicOfFocus { get; set; }
        public string GeographicTargetedAreas { get; set; }
        public string TargetAudience { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModBy { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    
        public virtual client client { get; set; }
        public virtual @case @case { get; set; }
    }
}
