//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaigncas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campaigncas()
        {
            this.campaignmaterials = new HashSet<campaignmaterial>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<System.DateTime> AdStartDate { get; set; }
        public Nullable<System.DateTime> AdEndDate { get; set; }
        public string AdType { get; set; }
        public string PlacedBy { get; set; }
        public string PublicationName { get; set; }
        public Nullable<int> PublicationCirculation { get; set; }
        public string ProgramName { get; set; }
        public Nullable<decimal> CostIndiviualRate { get; set; }
        public Nullable<decimal> CostGroupRate { get; set; }
        public string TopicOfFocus { get; set; }
        public string GeographicTargetedAreas { get; set; }
        public string TargetAudience { get; set; }
        public string Comments { get; set; }
    
        public virtual @case @case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<campaignmaterial> campaignmaterials { get; set; }
    }
}
