//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaignmaterial
    {
        public int ID { get; set; }
        public Nullable<int> CAMCaseID { get; set; }
        public Nullable<int> AttendeeID { get; set; }
        public string Fixturename { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual campaigncas campaigncas { get; set; }
        public virtual person person { get; set; }
    }
}
