//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientgridfield
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Code { get; set; }
        public string CodeText { get; set; }
        public string Name { get; set; }
        public string Caption { get; set; }
        public string Type { get; set; }
        public Nullable<int> FieldOrder { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public string Description { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<bool> WordWrap { get; set; }
    
        public virtual client client { get; set; }
    }
}
