//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumption
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> ConsumptionDate { get; set; }
        public Nullable<long> Consumption1 { get; set; }
    
        public virtual client client { get; set; }
        public virtual service service { get; set; }
    }
}
