//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicemodel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public devicemodel()
        {
            this.devices = new HashSet<device>();
            this.programdevicemodels = new HashSet<programdevicemodel>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string DeviceModelNumber { get; set; }
        public int DeviceTypeID { get; set; }
        public Nullable<int> EffLevelID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Version { get; set; }
        public Nullable<bool> IsNewDefault { get; set; }
        public string Size { get; set; }
        public string FlowRate { get; set; }
        public Nullable<float> ToiletGPF { get; set; }
        public Nullable<bool> ToiletAdaCompliant { get; set; }
        public Nullable<bool> ToiletUlfCompliant { get; set; }
        public string ToiletFlushType { get; set; }
        public Nullable<float> CwMEF { get; set; }
        public Nullable<float> CwWF { get; set; }
        public string XRayFilProType { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> ShowInSurvey { get; set; }
        public Nullable<int> MostEfficient { get; set; }
        public string ShowerHeadType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModDate { get; set; }
        public int ModBy { get; set; }
    
        public virtual client client { get; set; }
        public virtual devicetype devicetype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device> devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<programdevicemodel> programdevicemodels { get; set; }
    }
}
