//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public device()
        {
            this.interventions = new HashSet<intervention>();
            this.interventions1 = new HashSet<intervention>();
            this.surveyareas = new HashSet<surveyarea>();
            this.surveyareas1 = new HashSet<surveyarea>();
            this.surveyareas2 = new HashSet<surveyarea>();
            this.surveyareas3 = new HashSet<surveyarea>();
            this.surveyareas4 = new HashSet<surveyarea>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> DeviceModelID { get; set; }
        public string Manufacturer { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public Nullable<bool> CanRetrofit { get; set; }
        public string SerialNumber { get; set; }
        public string OperationalUse { get; set; }
        public Nullable<bool> EasilyAccessed { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> PurchaseStore { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string StoreNumber { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<decimal> VoucherAmount { get; set; }
        public Nullable<System.DateTime> VoucherRedeemDate { get; set; }
        public Nullable<System.DateTime> VoucherExpireDate { get; set; }
        public Nullable<bool> IsLeaking { get; set; }
        public Nullable<float> HoursUseDay { get; set; }
        public Nullable<int> ControllerStationsTotal { get; set; }
        public Nullable<int> ControllerStationsInUse { get; set; }
        public string PressureRegulatorPsi { get; set; }
        public Nullable<float> Gpm { get; set; }
        public Nullable<float> Gpf { get; set; }
        public Nullable<float> WF { get; set; }
        public Nullable<bool> HasAerator { get; set; }
        public Nullable<bool> Leaks { get; set; }
        public Nullable<bool> Drips { get; set; }
        public Nullable<bool> LowFlow { get; set; }
        public Nullable<bool> LeakingAtFlapper { get; set; }
        public Nullable<bool> FillValveFaulty { get; set; }
        public string PassFail { get; set; }
        public Nullable<int> ImportID { get; set; }
        public Nullable<int> ImportIDs { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModDate { get; set; }
        public int ModBy { get; set; }
    
        public virtual client client { get; set; }
        public virtual devicemodel devicemodel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<intervention> interventions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<intervention> interventions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surveyarea> surveyareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surveyarea> surveyareas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surveyarea> surveyareas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surveyarea> surveyareas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surveyarea> surveyareas4 { get; set; }
    }
}
