//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class educationalmaterial
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> EduCaseID { get; set; }
        public Nullable<System.DateTime> DistributionDate { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public string LocationType { get; set; }
        public string PreparedBy { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public string GeographicArea { get; set; }
        public string MaterialSent1 { get; set; }
        public Nullable<int> Quantity1 { get; set; }
        public string MaterialSent2 { get; set; }
        public Nullable<int> Quantity2 { get; set; }
        public string MaterialSent3 { get; set; }
        public Nullable<int> Quantity3 { get; set; }
        public string MaterialSent4 { get; set; }
        public Nullable<int> Quantity4 { get; set; }
        public string MaterialSent5 { get; set; }
        public Nullable<int> Quantity5 { get; set; }
        public string MaterialSent6 { get; set; }
        public Nullable<int> Quantity6 { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModBy { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    
        public virtual client client { get; set; }
        public virtual educationalvisitcas educationalvisitcas { get; set; }
        public virtual organization organization { get; set; }
        public virtual person person { get; set; }
    }
}
