//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class educationalvisitcas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public educationalvisitcas()
        {
            this.educationalmaterials = new HashSet<educationalmaterial>();
            this.educationalvisitattendees = new HashSet<educationalvisitattendee>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<System.DateTime> PlannedVisitDate { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Presenter { get; set; }
        public string EventType { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> NoOfAtendees { get; set; }
        public string Location { get; set; }
        public string Comments { get; set; }
        public string CommDist { get; set; }
        public string SubDivComName { get; set; }
        public string SubDivLegName { get; set; }
        public string WMDwaterManDisct { get; set; }
        public string OrganizationType { get; set; }
        public string Youth { get; set; }
        public string Grade { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress { get; set; }
        public string AdultType { get; set; }
        public string EICLocation { get; set; }
        public Nullable<bool> Partnership { get; set; }
        public string PartnerName { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> CostPerMaterial { get; set; }
        public Nullable<decimal> ExtendedCost { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModBy { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<educationalmaterial> educationalmaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<educationalvisitattendee> educationalvisitattendees { get; set; }
        public virtual person person { get; set; }
        public virtual organization organization { get; set; }
    }
}
