//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class educationalvisitattendee
    {
        public int ID { get; set; }
        public Nullable<int> EduCaseID { get; set; }
        public string AttendeeName { get; set; }
        public string Address { get; set; }
        public Nullable<int> NoOfResidents { get; set; }
        public string AwareProgram { get; set; }
    
        public virtual educationalvisitcas educationalvisitcas { get; set; }
    }
}
