//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public int CaseID { get; set; }
        public Nullable<int> ResponsibleID { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<System.DateTime> TargetDateEnd { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public Nullable<System.DateTime> ActualDateEnd { get; set; }
        public string Comments { get; set; }
        public Nullable<int> PreviousStepID { get; set; }
        public string PreviousStepName { get; set; }
        public Nullable<int> NewStepID { get; set; }
        public string NewStepName { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> StepChangeDate { get; set; }
        public string LandscapeInspected { get; set; }
        public Nullable<int> NumUnitsSurveyed { get; set; }
        public string Language { get; set; }
        public string EventTimeRange { get; set; }
        public string DevicesInstalled { get; set; }
        public string ClothesWasher { get; set; }
        public string LeakDetected { get; set; }
        public string DevicesPostInspected { get; set; }
        public Nullable<int> InspectorID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModDate { get; set; }
        public int ModBy { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual client client { get; set; }
        public virtual systemtype systemtype { get; set; }
        public virtual person person { get; set; }
        public virtual programstep programstep { get; set; }
        public virtual programstep programstep1 { get; set; }
    }
}
