//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generalsetting
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<bool> AllowPropertyEditing { get; set; }
        public Nullable<bool> ShowActivePhasesOnly { get; set; }
        public string LandingPage { get; set; }
        public string NewCaseDefaultPhase { get; set; }
        public Nullable<System.DateTime> DateLastBillingUpdate { get; set; }
        public Nullable<System.DateTime> DateNextPlannedBillingUpdate { get; set; }
    
        public virtual client client { get; set; }
    }
}
