//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class intervention
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public intervention()
        {
            this.surveyareas = new HashSet<surveyarea>();
            this.surveycases = new HashSet<surveycas>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public int CaseID { get; set; }
        public Nullable<int> InterventionTypeID { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> Subsidy { get; set; }
        public Nullable<System.DateTime> InterventionDate { get; set; }
        public Nullable<int> Repetitions { get; set; }
        public string Responsible { get; set; }
        public Nullable<long> PredictedWaterSavings { get; set; }
        public string WorkOrderNum { get; set; }
        public string Comments { get; set; }
        public string FundingType { get; set; }
        public Nullable<int> NewDeviceID { get; set; }
        public Nullable<int> OldDeviceID { get; set; }
        public string ProcessImpName { get; set; }
        public string ProcessImpDescription { get; set; }
        public string ProcessImpType { get; set; }
        public string WaterBroomAreaToClean { get; set; }
        public string UnitNo { get; set; }
        public Nullable<bool> IncludeInActualSavingsCalc { get; set; }
        public Nullable<decimal> TotalRecieptAmount { get; set; }
        public Nullable<decimal> TotalDeviceCost { get; set; }
        public Nullable<int> ImportID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModDate { get; set; }
        public int ModBy { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual client client { get; set; }
        public virtual device device { get; set; }
        public virtual device device1 { get; set; }
        public virtual systemtype systemtype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surveyarea> surveyareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surveycas> surveycases { get; set; }
    }
}
