//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymenthistory
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string PaymentMode { get; set; }
        public string CardHolderName { get; set; }
        public string StreetNo { get; set; }
        public string StreetName { get; set; }
        public string HoldingNumber { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<bool> IsAutoPayment { get; set; }
        public Nullable<bool> IsDebitCard { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> PaymentSuccess { get; set; }
        public string ResponseCode { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> ModBy { get; set; }
    
        public virtual client client { get; set; }
    }
}
