//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peoplepeopletype
    {
        public int ID { get; set; }
        public Nullable<int> PeopleID { get; set; }
        public Nullable<int> PeopleTypeID { get; set; }
    
        public virtual person person { get; set; }
        public virtual peopletype peopletype { get; set; }
    }
}
