//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class programstep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public programstep()
        {
            this.events = new HashSet<@event>();
            this.events1 = new HashSet<@event>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> DaysToNext { get; set; }
        public Nullable<int> DaysToExpire { get; set; }
        public Nullable<int> DaysToNotify { get; set; }
        public Nullable<int> NextStepID { get; set; }
        public string NestStepName { get; set; }
        public Nullable<int> StepOrder { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public string ActionComments { get; set; }
        public string ActionReportName { get; set; }
        public string ActionReportType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModDate { get; set; }
        public int ModBy { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@event> events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@event> events1 { get; set; }
        public virtual program program { get; set; }
        public virtual systemtype systemtype { get; set; }
        public virtual systemtype systemtype1 { get; set; }
    }
}
