//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertiesservice
    {
        public int ID { get; set; }
        public int PropertyID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual property property { get; set; }
        public virtual service service { get; set; }
    }
}
