//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Number { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
    
        public virtual client client { get; set; }
    }
}
