//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.consumptions = new HashSet<consumption>();
            this.meterreads = new HashSet<meterread>();
            this.propertiesservices = new HashSet<propertiesservice>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string SvcNumber { get; set; }
        public string PremiseNum { get; set; }
        public string AcctNumber { get; set; }
        public string AccountBase { get; set; }
        public string Block { get; set; }
        public string Lot { get; set; }
        public string SvcType { get; set; }
        public string SvcSize { get; set; }
        public string Status { get; set; }
        public string StreetNo { get; set; }
        public Nullable<int> StreetNoFrom { get; set; }
        public Nullable<int> StreetNoTo { get; set; }
        public string StreetName { get; set; }
        public string StreetSuffix { get; set; }
        public string StreetDir { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> DateSvcInstall { get; set; }
        public Nullable<System.DateTime> DateSvcRenew { get; set; }
        public Nullable<System.DateTime> DateSvcEnd { get; set; }
        public string SPResivoirCode { get; set; }
        public string FlagMultiTap { get; set; }
        public string FlagMultiMtr { get; set; }
        public string DistrictID { get; set; }
        public string DescWhatMtrServs { get; set; }
        public string StructureDesc { get; set; }
        public string MainDirection { get; set; }
        public string TapDirection { get; set; }
        public string MtrDirection { get; set; }
        public string MainNumFeet { get; set; }
        public string MainAddrDir1 { get; set; }
        public string MainAddrDir2 { get; set; }
        public string MainAddrBase { get; set; }
        public string MainAddrStreet { get; set; }
        public string MainAddrSffx { get; set; }
        public string TapNumFeet { get; set; }
        public string TapAddrDir1 { get; set; }
        public string TapAddrDir2 { get; set; }
        public string TapAddrBase { get; set; }
        public string TapAddrStreet { get; set; }
        public string TapAddrSffx { get; set; }
        public string TapType { get; set; }
        public string TapBlock { get; set; }
        public string TapNumber { get; set; }
        public string MtrConnectionNum { get; set; }
        public string MtrNumber { get; set; }
        public string MtrType { get; set; }
        public string MtrSize { get; set; }
        public string MtrMake { get; set; }
        public string MtrConnectionLocn { get; set; }
        public string MtrReaderComments { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string Route { get; set; }
        public string Sequence { get; set; }
        public string PremiseNumOLD { get; set; }
        public Nullable<bool> LockUpdate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModDate { get; set; }
        public int ModBy { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumption> consumptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meterread> meterreads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<propertiesservice> propertiesservices { get; set; }
    }
}
