//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supportticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supportticket()
        {
            this.ticketattachments = new HashSet<ticketattachment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> TicketDate { get; set; }
        public Nullable<int> RequesterID { get; set; }
        public string Title { get; set; }
        public string Priority { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ResolvedID { get; set; }
        public Nullable<System.DateTime> ResolveDate { get; set; }
        public string ResolverComments { get; set; }
        public string TicketStatus { get; set; }
    
        public virtual client client { get; set; }
        public virtual contact contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticketattachment> ticketattachments { get; set; }
    }
}
