//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class surveycas
    {
        public int ID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> InterventionID { get; set; }
        public Nullable<int> SurveyTypeID { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<int> NumberOfOcupants { get; set; }
        public Nullable<int> NumberOfSimilarUnits { get; set; }
        public string PassFail { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModBy { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual client client { get; set; }
        public virtual intervention intervention { get; set; }
        public virtual systemtype systemtype { get; set; }
    }
}
