//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class violationcas
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public int CaseID { get; set; }
        public string CitationNumber { get; set; }
        public Nullable<decimal> FineAmount { get; set; }
        public Nullable<System.DateTime> ViolationDateTime { get; set; }
        public Nullable<System.DateTime> ViolationDateTime2 { get; set; }
        public Nullable<System.DateTime> ComplianceDate { get; set; }
        public string ViolationDescription { get; set; }
        public string AdditionalDescription { get; set; }
        public string CorrectiveAction { get; set; }
        public string AdditionalAction { get; set; }
        public string PhotoEvidence1 { get; set; }
        public string PhotoEvidence2 { get; set; }
        public Nullable<bool> SourceSprinkler { get; set; }
        public Nullable<bool> SourceHose { get; set; }
        public Nullable<bool> SourceHoseSprinkler { get; set; }
        public Nullable<bool> SourceCurb { get; set; }
        public Nullable<bool> SourcePipe { get; set; }
        public Nullable<bool> SourceUnknown { get; set; }
        public Nullable<bool> SourceAfterHours { get; set; }
        public Nullable<bool> Runoff { get; set; }
        public Nullable<bool> GoingToStreet { get; set; }
        public Nullable<bool> GoingToDriveway { get; set; }
        public Nullable<bool> GoingToSideWalk { get; set; }
        public Nullable<bool> GoingToGutter { get; set; }
        public Nullable<bool> GoingToAlley { get; set; }
        public Nullable<bool> GoingToOther { get; set; }
        public string ViolatorGender { get; set; }
        public string ViolatorType { get; set; }
        public Nullable<bool> InCity { get; set; }
        public Nullable<int> InspectorID { get; set; }
        public Nullable<int> ContactPersonID { get; set; }
        public Nullable<int> ViolationCodeID { get; set; }
        public string SourceOfWater { get; set; }
        public string Observer { get; set; }
        public Nullable<System.DateTime> DatePlannedCuttoff { get; set; }
        public Nullable<System.DateTime> DateActualCuttoff { get; set; }
        public Nullable<int> DaysToWater { get; set; }
        public string TimesToWater { get; set; }
        public Nullable<int> CustomerViolationNumber { get; set; }
        public Nullable<bool> NotAViolation { get; set; }
        public string NotAViolationReason { get; set; }
        public string NotAViolationOtherReason { get; set; }
        public string PhotoEvidence1Patroller { get; set; }
        public string PhotoEvidence2Patroller { get; set; }
        public string InitialContactPatroller { get; set; }
        public Nullable<System.DateTime> InitialContactDateTime { get; set; }
        public string InitialContactComments { get; set; }
        public string FollowupContactPatroller { get; set; }
        public Nullable<System.DateTime> FollowupContactDateTime { get; set; }
        public string FollowupContactComments { get; set; }
        public string ReportSource { get; set; }
        public Nullable<bool> LargeUser { get; set; }
        public Nullable<int> LetterNumber { get; set; }
        public Nullable<bool> cbkShutoff { get; set; }
        public Nullable<System.DateTime> DateShutoff { get; set; }
        public Nullable<bool> cbkFlowRestrictor { get; set; }
        public Nullable<System.DateTime> DateFlowRestrictor { get; set; }
        public Nullable<System.DateTime> ViolationDateTimeNew { get; set; }
        public string OtherViolationType { get; set; }
        public string ViolationNumber { get; set; }
        public string WhatObserved { get; set; }
        public string DateMailed { get; set; }
        public string ViolationSent { get; set; }
        public Nullable<int> NumPropertyViolation { get; set; }
        public Nullable<System.DateTime> RemovedDate { get; set; }
        public Nullable<System.DateTime> RestoredDate { get; set; }
        public Nullable<System.DateTime> RestorePaidDate { get; set; }
        public Nullable<System.DateTime> DateComplianceDue { get; set; }
        public string VTNNumber { get; set; }
        public Nullable<bool> IsSentToSpecialMagistrate { get; set; }
        public Nullable<System.DateTime> SentToSpecialMagistrateDate { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual client client { get; set; }
        public virtual person person { get; set; }
        public virtual person person1 { get; set; }
        public virtual violationcode violationcode { get; set; }
    }
}
