//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class waterconsEntities : DbContext
    {
        public waterconsEntities()
            : base("name=waterconsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<advertisementcas> advertisementcases { get; set; }
        public virtual DbSet<applicationmenu> applicationmenus { get; set; }
        public virtual DbSet<campaigncas> campaigncases { get; set; }
        public virtual DbSet<campaignmaterial> campaignmaterials { get; set; }
        public virtual DbSet<casecontact> casecontacts { get; set; }
        public virtual DbSet<@case> cases { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<clientgridfield> clientgridfields { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<consumption> consumptions { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<deviceefficiencylevel> deviceefficiencylevels { get; set; }
        public virtual DbSet<devicemodel> devicemodels { get; set; }
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<devicetype> devicetypes { get; set; }
        public virtual DbSet<documentation> documentations { get; set; }
        public virtual DbSet<documentcontent> documentcontents { get; set; }
        public virtual DbSet<documentupload> documentuploads { get; set; }
        public virtual DbSet<educationalmaterial> educationalmaterials { get; set; }
        public virtual DbSet<educationalvisitattendee> educationalvisitattendees { get; set; }
        public virtual DbSet<educationalvisitcas> educationalvisitcases { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<generalsetting> generalsettings { get; set; }
        public virtual DbSet<gridfield> gridfields { get; set; }
        public virtual DbSet<intervention> interventions { get; set; }
        public virtual DbSet<irrigationalcas> irrigationalcases { get; set; }
        public virtual DbSet<listitem> listitems { get; set; }
        public virtual DbSet<meterread> meterreads { get; set; }
        public virtual DbSet<newslettercontact> newslettercontacts { get; set; }
        public virtual DbSet<newsletter> newsletters { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<peoplepeopletype> peoplepeopletypes { get; set; }
        public virtual DbSet<peopletype> peopletypes { get; set; }
        public virtual DbSet<phase> phases { get; set; }
        public virtual DbSet<programdevicemodel> programdevicemodels { get; set; }
        public virtual DbSet<programdevicetype> programdevicetypes { get; set; }
        public virtual DbSet<programinterventiontype> programinterventiontypes { get; set; }
        public virtual DbSet<program> programs { get; set; }
        public virtual DbSet<programstep> programsteps { get; set; }
        public virtual DbSet<property> properties { get; set; }
        public virtual DbSet<propertiesservice> propertiesservices { get; set; }
        public virtual DbSet<propertyowner> propertyowners { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<savingsfactor> savingsfactors { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<servicetype> servicetypes { get; set; }
        public virtual DbSet<supportticket> supporttickets { get; set; }
        public virtual DbSet<surveyarea> surveyareas { get; set; }
        public virtual DbSet<surveycas> surveycases { get; set; }
        public virtual DbSet<systemtype> systemtypes { get; set; }
        public virtual DbSet<ticketattachment> ticketattachments { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<violationcas> violationcases { get; set; }
        public virtual DbSet<violationcode> violationcodes { get; set; }
        public virtual DbSet<waterrate> waterrates { get; set; }
        public virtual DbSet<paymenthistory> paymenthistories { get; set; }
        public virtual DbSet<activitylog> activitylogs { get; set; }
        public virtual DbSet<package> packages { get; set; }
    }
}
