//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCons.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class waterrate
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string PropType { get; set; }
        public string SICCode { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> BottomLimit { get; set; }
        public Nullable<int> TopLimit { get; set; }
        public Nullable<decimal> LevelRate { get; set; }
    
        public virtual client client { get; set; }
    }
}
